-- -- If Pitbull is loaded, and there's a profile called "XervishUI"
-- -- Detect spec changes, and then set the profiles appropriately.
-- local function xUF_Handle_Role_Change()
--     -- Only do this if Pitbull is loaded (addons will have loaded by this time):
--     if IsAddOnLoaded("PitBull4") then
--         -- Check if our profile exists:
--         if _G.PitBull4DB.profiles.XervishUI then
--             -- Get info about our current spec and role:
--             local name = select(2, GetSpecializationInfo(GetSpecialization()))
--             local role =  GetSpecializationRole(GetSpecialization())

--             if role == "HEALER" then
--                 print("Showing Healer Frames")
--                 _G.PitBull4DB.profiles.XervishUI.groups.DPSParty.enabled = false
--                 _G.PitBull4DB.profiles.XervishUI.groups.DPSRaid.enabled = false
--                 _G.PitBull4DB.profiles.XervishUI.groups.HealingParty.enabled = true
--                 _G.PitBull4DB.profiles.XervishUI.groups.HealingRaid.enabled = true
--             else
--                 print("Showing DPS/Tank Frames")
--                 _G.PitBull4DB.profiles.XervishUI.groups.DPSParty.enabled = true
--                 _G.PitBull4DB.profiles.XervishUI.groups.DPSRaid.enabled = true
--                 _G.PitBull4DB.profiles.XervishUI.groups.HealingParty.enabled = false
--                 _G.PitBull4DB.profiles.XervishUI.groups.HealingRaid.enabled = false
--             end

--             -- Make Pitbull Redraw things:
--             -- _G.PitBull4.GroupHeader:Update()
--         end
--     else
--         -- Do nothing!
--         return
--     end
-- end

-- rLib:RegisterCallback("PLAYER_LOGIN", xUF_Handle_Role_Change)
-- rLib:RegisterCallback("PLAYER_SPECIALIZATION_CHANGED", xUF_Handle_Role_Change)
